/**
 * Fineli food database client — uses the local Open Data index (no API calls).
 *
 * All food data comes from the pre-built index.json generated by
 * scripts/build-fineli-index.ts from Fineli CSV data.
 *
 * The public interface (searchFoods, getFood, getComponents) is preserved
 * so all existing consumers (engine, routes, tests) work unchanged.
 */

import {
  FineliFood,
  FineliComponent,
  COMPONENT_ORDER,
} from '@/types';
import {
  searchFoods as localSearchFoods,
  getFoodDetails,
} from './local-index';

interface FineliClientConfig {
  defaultLang?: 'fi' | 'en' | 'sv';
  /** @deprecated No longer used — kept for backwards compatibility */
  baseUrl?: string;
  /** @deprecated No longer used — kept for backwards compatibility */
  cache?: unknown;
}

export class FineliClient {
  private defaultLang: 'fi' | 'en' | 'sv';

  constructor(config?: FineliClientConfig) {
    this.defaultLang = config?.defaultLang ?? 'fi';
  }

  /**
   * Search foods by name. Uses the local Fineli index — instant, no API call.
   */
  async searchFoods(query: string, _lang?: string): Promise<FineliFood[]> {
    return localSearchFoods(query, _lang ?? this.defaultLang);
  }

  /**
   * Get full food details by Fineli ID. Uses the local index.
   */
  async getFood(id: number): Promise<FineliFood> {
    const food = getFoodDetails(id);
    if (!food) {
      throw new Error(`Food not found in local index: ${id}`);
    }
    return food;
  }

  /**
   * Get component definitions. Returns the standard Fineli component list.
   */
  async getComponents(): Promise<FineliComponent[]> {
    return COMPONENT_ORDER.map((code, i) => ({
      id: i + 1,
      code,
      nameFi: code,
      nameEn: code,
      unit: 'g',
    }));
  }
}
